DEBUG 2024-09-27 02:24:27.941 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:24:27.941 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:24:27.941 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:24:27.942 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:24:27.942 UTC: 	 Error: ParkingSingleMuon0_2022C/crab_project/crab_240927_ParkingSingleMuon0_2022C is not a valid CRAB project directory.
ERROR 2024-09-27 02:24:27.942 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon0_2022C/crab_project/crab_240927_ParkingSingleMuon0_2022C is not a valid CRAB project directory.
INFO 2024-09-27 02:24:27.946 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
DEBUG 2024-09-27 02:24:29.826 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:24:29.827 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:24:29.827 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:24:29.827 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:24:29.828 UTC: 	 Error: ParkingSingleMuon1_2022C/crab_project/crab_240927_ParkingSingleMuon1_2022C is not a valid CRAB project directory.
ERROR 2024-09-27 02:24:29.828 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon1_2022C/crab_project/crab_240927_ParkingSingleMuon1_2022C is not a valid CRAB project directory.
INFO 2024-09-27 02:24:29.830 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
DEBUG 2024-09-27 02:24:31.728 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:24:31.729 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:24:31.729 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:24:31.729 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:24:31.729 UTC: 	 Error: ParkingSingleMuon2_2022C/crab_project/crab_240927_ParkingSingleMuon2_2022C is not a valid CRAB project directory.
ERROR 2024-09-27 02:24:31.730 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon2_2022C/crab_project/crab_240927_ParkingSingleMuon2_2022C is not a valid CRAB project directory.
INFO 2024-09-27 02:24:31.732 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
DEBUG 2024-09-27 02:24:33.530 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:24:33.531 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:24:33.531 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:24:33.531 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:24:33.531 UTC: 	 Error: ParkingSingleMuon0_2022D/crab_project/crab_240927_ParkingSingleMuon0_2022D is not a valid CRAB project directory.
ERROR 2024-09-27 02:24:33.532 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon0_2022D/crab_project/crab_240927_ParkingSingleMuon0_2022D is not a valid CRAB project directory.
INFO 2024-09-27 02:24:33.533 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
DEBUG 2024-09-27 02:24:35.314 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:24:35.315 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:24:35.315 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:24:35.315 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:24:35.315 UTC: 	 Error: ParkingSingleMuon1_2022D/crab_project/crab_240927_ParkingSingleMuon1_2022D is not a valid CRAB project directory.
ERROR 2024-09-27 02:24:35.316 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon1_2022D/crab_project/crab_240927_ParkingSingleMuon1_2022D is not a valid CRAB project directory.
INFO 2024-09-27 02:24:35.317 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
DEBUG 2024-09-27 02:24:37.144 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:24:37.145 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:24:37.145 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:24:37.145 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:24:37.145 UTC: 	 Error: ParkingSingleMuon2_2022D/crab_project/crab_240927_ParkingSingleMuon2_2022D is not a valid CRAB project directory.
ERROR 2024-09-27 02:24:37.146 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon2_2022D/crab_project/crab_240927_ParkingSingleMuon2_2022D is not a valid CRAB project directory.
INFO 2024-09-27 02:24:37.147 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
DEBUG 2024-09-27 02:24:38.965 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:24:38.965 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:24:38.965 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:24:38.965 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:24:38.966 UTC: 	 Error: ParkingSingleMuon0_2022E/crab_project/crab_240927_ParkingSingleMuon0_2022E is not a valid CRAB project directory.
ERROR 2024-09-27 02:24:38.966 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon0_2022E/crab_project/crab_240927_ParkingSingleMuon0_2022E is not a valid CRAB project directory.
INFO 2024-09-27 02:24:38.968 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
DEBUG 2024-09-27 02:24:41.006 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:24:41.006 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:24:41.006 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:24:41.006 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:24:41.007 UTC: 	 Error: ParkingSingleMuon1_2022E/crab_project/crab_240927_ParkingSingleMuon1_2022E is not a valid CRAB project directory.
ERROR 2024-09-27 02:24:41.007 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon1_2022E/crab_project/crab_240927_ParkingSingleMuon1_2022E is not a valid CRAB project directory.
INFO 2024-09-27 02:24:41.009 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
DEBUG 2024-09-27 02:24:42.878 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:24:42.878 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:24:42.878 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:24:42.879 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:24:42.879 UTC: 	 Error: ParkingSingleMuon2_2022E/crab_project/crab_240927_ParkingSingleMuon2_2022E is not a valid CRAB project directory.
ERROR 2024-09-27 02:24:42.879 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon2_2022E/crab_project/crab_240927_ParkingSingleMuon2_2022E is not a valid CRAB project directory.
INFO 2024-09-27 02:24:42.881 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
DEBUG 2024-09-27 02:25:03.915 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-27 02:25:03.916 UTC: 	 Running on: Linux lxplus817.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-09-27 02:25:03.916 UTC: 	 Executing command: 'status'
DEBUG 2024-09-27 02:25:03.916 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2024-09-27 02:25:03.916 UTC: 	 Error: ParkingSingleMuon0_2022C/crab_project/crab_240927_ParkingSingleMuon0_2022C is not a valid CRAB project directory.
ERROR 2024-09-27 02:25:03.917 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ParkingSingleMuon0_2022C/crab_project/crab_240927_ParkingSingleMuon0_2022C is not a valid CRAB project directory.
INFO 2024-09-27 02:25:03.918 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.09.20/CMSSW_12_4_21/src/ZprimeTo4l/MergedLepton/test/24.09.27/crab.log
